### ISSUE TITLE
pip_search xxxx return AttributeError: 'NoneType' object has not attribute 'find'

### ISSUE THREAD

**Issue by BiyuHuang** [victorgarric/pip_search#27]
(venv_20220513) ➜ python pip_search pyspark
```
Traceback (most recent call last):
  File "python/venv_20220513/bin/pip_search", line 8, in <module>
    sys.exit(main())
  File "python/venv_20220513/lib/python3.8/site-packages/pip_search/__main__.py", line 65, in main
    for package in result:
  File "python/venv_20220513/lib/python3.8/site-packages/pip_search/pip_search.py", line 103, in search
    snippet.select_one('span[class*="released"]').find("time")[
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by BiyuHuang** [comment]
(venv_20220513) ➜  python pip_search pyspark
```
Traceback (most recent call last):
  File "/Users/biyu.huang/workspace/code_sp/python/venv_20220513/bin/pip_search", line 8, in <module>
    sys.exit(main())
  File "/Users/biyu.huang/workspace/code_sp/python/venv_20220513/lib/python3.8/site-packages/pip_search/__main__.py", line 65, in main
    for package in result:
  File "/Users/biyu.huang/workspace/code_sp/python/venv_20220513/lib/python3.8/site-packages/pip_search/pip_search.py", line 103, in search
    snippet.select_one('span[class*="released"]').find("time")[
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by paulfwhite** [comment]
Do you mean "has no attribute" ?

**Comment by BiyuHuang** [comment]
noted it, thanks for help!
