### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by kristofwillen** [victorgarric/pip_search#28]
When running pip_search, I receive the following error:

```bash
$ pip_search git
Traceback (most recent call last):
  File "/usr/local/bin/pip_search", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/pip_search/__main__.py", line 65, in main
    for package in result:
  File "/usr/local/lib/python3.10/site-packages/pip_search/pip_search.py", line 103, in search
    snippet.select_one('span[class*="released"]').find("time")[
AttributeError: 'NoneType' object has no attribute 'find'
```

Tried again in a clean pipenv venv, same result. 

Installed version & deps: 
```bash
$ pipenv graph
pip-search==0.0.11
  - bs4 [required: Any, installed: 0.0.1]
    - beautifulsoup4 [required: Any, installed: 4.11.1]
      - soupsieve [required: >1.2, installed: 2.3.2.post1]
  - requests [required: Any, installed: 2.27.1]
    - certifi [required: >=2017.4.17, installed: 2021.10.8]
    - charset-normalizer [required: ~=2.0.0, installed: 2.0.12]
    - idna [required: >=2.5,<4, installed: 3.3]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.9]
  - rich [required: Any, installed: 12.4.1]
    - commonmark [required: >=0.9.0,<0.10.0, installed: 0.9.1]
    - pygments [required: >=2.6.0,<3.0.0, installed: 2.12.0]
```

Python version used = 3.10.4

**Comment by kristofwillen** [comment]
And I now see it's a double bugreport entry of #26 
Please ignore.
