### ISSUE TITLE
AttributeError find

### ISSUE THREAD

**Issue by m1st0** [victorgarric/pip_search#29]
Environment: Python 3.10 on Ubuntu 22.04
Install location: ~/.local/lib/python3.10/site-packages/pip_search
Calling path: ~/.local/bin/pip_search

When searching, the following error appears:
<pre>
Traceback (most recent call last):
  File "/home/me/.local/bin/pip_search", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/pip_search/__main__.py", line 65, in main
    for package in result:
  File "/home/me/.local/lib/python3.10/site-packages/pip_search/pip_search.py", line 103, in search
    snippet.select_one('span[class*="released"]').find("time")[
AttributeError: 'NoneType' object has no attribute 'find'`
</pre>

**Comment by wookayin** [comment]
See #26.

**Comment by m1st0** [comment]
May not be necessary but confirmed the fix in #26 .
