### ISSUE TITLE
pip_search error in terminal

### ISSUE THREAD

**Issue by Edenzzzz** [victorgarric/pip_search#31]
Env:
Anaconda 2020.02 on win10
Python 3.7.6

Typed in pip_search in the terminal
The error appears to be a version compatibility problem.

Error:
Traceback (most recent call last):
  File "c:\users\19051\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\19051\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\19051\anaconda3\Scripts\pip_search.exe\__main__.py", line 7, in <module>
  File "c:\users\19051\anaconda3\lib\site-packages\pip_search\__main__.py", line 65, in main
    for package in result:
  File "c:\users\19051\anaconda3\lib\site-packages\pip_search\pip_search.py", line 103, in search
    snippet.select_one('span[class*="released"]').find("time")[
AttributeError: 'NoneType' object has no attribute 'find'

Thanks for your help!

**Comment by victorgarric** [comment]
Fixed with 0.0.12 version 

`pip install pip_search --upgrade`
