### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by GF-Huang** [victorgarric/pip_search#42]
```
pip_search 0.0.10

(mlagents) C:\Users\jokeh>pip_search multiprocess
Traceback (most recent call last):
  File "C:\Users\jokeh\miniconda3\envs\mlagents\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jokeh\miniconda3\envs\mlagents\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jokeh\miniconda3\envs\mlagents\Scripts\pip_search.exe\__main__.py", line 7, in <module>
  File "C:\Users\jokeh\miniconda3\envs\mlagents\lib\site-packages\pip_search\__main__.py", line 65, in main
    for package in result:
  File "C:\Users\jokeh\miniconda3\envs\mlagents\lib\site-packages\pip_search\pip_search.py", line 98, in search
    snippet.select_one('span[class*="package-snippet__version"]').text.strip(),
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by victorgarric** [comment]
Your version, 0.0.10, is outdated. Consider updating:

`pip install pip_search --upgrade`
